AdirKuhn\UserBundle\Entity\User:
    type: entity
    table: User
    repositoryClass: AdirKuhn\UserBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255
        isActive:
            type: boolean
    lifecycleCallbacks: {  }
